### ISSUE TITLE
Ledger hardware wallet make app not close correctly

### ISSUE THREAD

**Issue by stellarchat** [stellarchat/desktop-client#261]
It can be reproduced on win10 without ledger hardware installed.

When start, an error will show in console:

> Error: A dynamic link library (DLL) initialization routine failed.
> \\?\D:\dev\foxlet\node_modules\node-hid\build\Release\HID.node
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
>     at Object.Module._extensions..node (module.js:671:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
>     at Module.load (module.js:561:32)
>     at tryModuleLoad (module.js:504:12)
>     at Function.Module._load (module.js:496:3)
>     at Module.require (module.js:586:17)
>     at require (internal/module.js:11:18)
>     at bindings (D:\dev\foxlet\node_modules\bindings\bindings.js:81:44)
>     at loadBinding (D:\dev\foxlet\node_modules\node-hid\nodehid.js:16:38)
>     at Object.showdevices [as devices] (D:\dev\foxlet\node_modules\node-hid\nodehid.js:132:5)
>     at getDevices (D:\dev\foxlet\node_modules\@ledgerhq\hw-transport-node-hid\lib\getDevices.js:19:28)
>     at Function.TransportNodeHid.listen (D:\dev\foxlet\node_modules\@ledgerhq\hw-transport-node-hid\lib\TransportNodeHid.js:414:54)
>     at Function.module.exports.HardwareWalletLedger.init (D:\dev\foxlet\src\main\hardwareWalletLedger.js:310:59)
>     **at App.<anonymous> (D:\dev\foxlet\main.js:155:26)**
>     at emitTwo (events.js:131:20)

When close, a error dialog would be pop up:

> "Electron" has stopped working.
>  A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.
>                                                                                                             CLOSE PROGRAM.  

The console show "error Command failed with exit code 255."

**Comment by stellarchat** [comment]
@Akuukis Would it possible the app could check whether user installed ledger hardware. If not, do not init the HardwareWalletLedger.

**Comment by Akuukis** [comment]
Most likely related, Ledger dependencies were not included in the build package. See the fix in #262
@stellarchat Let me know if that also fixes this.
